[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "DUUQHQtpkN"
weight = 9_999

[[main]]
name = "Categories"
pageRef = "categories"
identifier = "1zBPn4sGAy"
weight = 9_999

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "PdSgwrpDMc"
weight = 9_999

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"
identifier = "EcHKFMaqsA"
weight = 9_999

[[footer]]
name = "Categories"
pageRef = "categories"
identifier = "ZuLQygoeDV"
weight = 9_999
